# Generated by Django 4.1.13 on 2024-11-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alimento',
            name='calorias_unidade',
            field=models.CharField(default='KCAL', help_text='Unidade de calorias', max_length=10),
        ),
        migrations.AddField(
            model_name='alimento',
            name='carboidratos_unidade',
            field=models.CharField(default='g', help_text='Unidade de carboidratos', max_length=10),
        ),
        migrations.AddField(
            model_name='alimento',
            name='gorduras_unidade',
            field=models.CharField(default='g', help_text='Unidade de gorduras', max_length=10),
        ),
        migrations.AddField(
            model_name='alimento',
            name='proteinas_unidade',
            field=models.CharField(default='g', help_text='Unidade de proteínas', max_length=10),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.FloatField(blank=True, help_text='Calorias (KCAL)', null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carboidratos',
            field=models.FloatField(blank=True, help_text='Carboidratos (g)', null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='gorduras',
            field=models.FloatField(blank=True, help_text='Gorduras (g)', null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(blank=True, help_text='Proteínas (g)', null=True),
        ),
    ]
