# Generated by Django 4.1.13 on 2024-11-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_alimento_calorias_unidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='calorias_unidade',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='carboidratos_unidade',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='gorduras_unidade',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='proteinas_unidade',
        ),
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carboidratos',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='gorduras',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alimento',
            name='proteinas',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
