# Generated by Django 4.1.13 on 2024-11-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0003_remove_alimento_calorias_unidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alimento',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='gorduras',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='indice_glicemico',
        ),
        migrations.RemoveField(
            model_name='alimento',
            name='proteinas',
        ),
        migrations.AddField(
            model_name='alimento',
            name='g_ou_ml',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alimento',
            name='medida_usual',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='calorias',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='carboidratos',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='alimento',
            name='nome',
            field=models.CharField(max_length=255),
        ),
    ]
