# Generated by Django 3.1.12 on 2025-01-20 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0004_remove_alimento_categoria_remove_alimento_gorduras_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alimento',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
